#!/usr/bin/env python3
"""Turn the spec's vectors.json into test/vectors_data.ml, so the tests need no JSON parser.

Usage: python3 tools/gen_vectors.py path/to/vectors.json > test/vectors_data.ml
"""
import json
import sys


def words(ws):
    return "[| " + "; ".join(f"0x{w}" for w in ws) + " |]"


def pairs(d, conv=lambda x: x):
    return "[ " + "; ".join(f"({k}, {conv(x)})" for k, x in d.items()) + " ]"


def main(path):
    v = json.load(open(path))
    out = ["(* Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit. *)"]
    out.append(f"let k = {v['K']}")
    out.append(f"let key = {words(v['key'])}")
    out.append("(* o, h, o_out, h_out *)")
    out.append("let t_vectors = [")
    for t in v["T"]:
        out.append(f"  ({words(t['o'])}, {words(t['h'])}, {words(t['o_out'])}, {words(t['h_out'])});")
    out.append("]")
    out.append("(* counter, o, h *)")
    out.append("let f_vectors = [")
    for f in v["F"]:
        assert f["domain"] == "DOMAIN_STREAM" and f["aux"] == "AUX_STREAM"
        out.append(f"  ({f['counter']}, {words(f['o'])}, {words(f['h'])});")
    out.append("]")
    out.append("let stream = [")
    for s in v["stream_words"]:
        out.append(f"  ({s['first_word']}, {words(s['words'])});")
    out.append("]")
    d = v["draws_from_position_0"]
    out.append(f"let f64 = {pairs(d['Float64'], repr)}")
    out.append(f"let f32 = {pairs(d['Float32'], repr)}")
    out.append(f"let bool = {pairs(d['Bool'], lambda x: str(bool(x)).lower())}")
    k = v["derived_keys"]
    out.append(f"let split0 = {words(k['split_child_0'])}")
    out.append(f"let split1 = {words(k['split_child_1'])}")
    out.append(f"let fork0 = {words(k['fork_child_0_at_block_0'])}")
    out.append(f"let purpose7 = {words(k['purpose_7'])}")
    s = v["seed_whitening"]
    out.append(f"let seed = {s['seed']}")
    out.append(f"let seed_key = {words(s['key'])}")
    out.append(f"let seed_f64 = {pairs(s['Float64'], repr)}")
    out.append(f"let seed_u32 = {pairs(s['UInt32'], lambda x: '0x' + x)}")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
