#!/usr/bin/env python3
"""OCaml fixtures for test/derived.ml from tandem-c's cross-check headers, which tandem-c
generates from the shared device core (tandem-cuda core.hpp).

    python3 tools/gen_derived.py ../tandem-c/tests > test/derived_data.ml
"""
import re
import sys

tests = sys.argv[1]


def read(name):
    with open(f"{tests}/{name}") as f:
        return f.read()


def num(v, suffix):
    v = int(v.strip().rstrip("ul"))
    if suffix == "L":
        v = v - (1 << 64) if v >= 1 << 63 else v
        return f"({v}L)"
    return str(v)


def ints(vals, suffix):
    return "; ".join(num(v, suffix) for v in vals.split(","))


def bounded(text, array, suffix, start=False):
    # Entries are `{n, {values}, end_pos}`, or `{start, n, {values}, end_pos}` for fills.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    lead = r"(\d+)ull, " if start else ""
    rows = []
    for m in re.findall(rf"\{{{lead}(\d+)u(?:ll)?,\s*\{{([^}}]*)\}},\s*(\d+)u\}}", body):
        *head, n, vals, end = m
        head = f"{head[0]}, " if head else ""
        rows.append(f"  ({head}{num(n, suffix)}, [| {ints(vals, suffix)} |], {end});")
    return "\n".join(rows)


def lit(v):
    v = v.strip().rstrip("f")
    return v if any(c in v for c in ".en") else v + "."


def floats(body):
    return "; ".join(lit(v) for v in body.replace("\n", " ").split(",") if v.strip())


def exponential(text, array):
    # Entries are `{start, {values}, end_pos}`.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    rows = []
    for start, vals, end in re.findall(r"\{(\d+)ull,\s*\{([^}]*)\},\s*(\d+)ull\}", body):
        rows.append(f"  ({start}, [| {floats(vals)} |], {end});")
    return "\n".join(rows)


below = read("cross_below.h")
fill_below = read("cross_fill_below.h")
normal = read("cross_normal.h")
expo = read("cross_exponential.h")
doubles = re.search(r"CROSS_NORMAL\[[^\]]*\] = \{(.*?)\};", normal, re.S).group(1)
end64 = re.search(r"CROSS_NORMAL_END_POS = (\d+)u", normal).group(1)
singles = re.search(r"CROSS_NORMALF\[[^\]]*\] = \{(.*?)\};", normal, re.S).group(1)
end32 = re.search(r"CROSS_NORMALF_END_POS = (\d+)u", normal).group(1)

print("(* Generated by tools/gen_derived.py from tandem-c's cross-check headers. Do not edit.")
print("   Each bounded and normal case starts from [Tandem.seed 42] after one [bool] draw. Each")
print("   exponential case starts from [Tandem.seed 42] at its start position. *)\n")
print("(* bound, draws, position after *)")
print(f"let below32 = [\n{bounded(below, 'CROSS_U32', '')}\n]\n")
print(f"let below64 = [\n{bounded(below, 'CROSS_U64', 'L')}\n]\n")
print("(* start position, bound, draws, position after *)")
print(f"let fill_below32 = [\n{bounded(fill_below, 'CROSS_FILL_U32', '', True)}\n]\n")
print(f"let fill_below64 = [\n{bounded(fill_below, 'CROSS_FILL_U64', 'L', True)}\n]\n")
print("(* normal2 pairs, flattened, and the position after *)")
print(f"let normal64 = ([| {floats(doubles)} |], {end64})")
print(f"let normal32 = ([| {floats(singles)} |], {end32})\n")
print("(* start position, draws, position after *)")
print(f"let exponential64 = [\n{exponential(expo, 'CROSS_EXPONENTIAL')}\n]\n")
print(f"let exponential32 = [\n{exponential(expo, 'CROSS_EXPONENTIALF')}\n]")
